<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>studystash</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudyStash.Core\StudyStash.Core.csproj" />
    <ProjectReference Include="..\StudyStash.Library\StudyStash.Library.csproj" />
  </ItemGroup>

</Project>
